### ISSUE TITLE
Permanenet BlueMap server

### ISSUE THREAD

**Issue by WojtekK78** [oddlama/minecraft-server#11]
Quick question how to permanently enable BlueMap server not to shutdown ? 
It should be as per info _"If you have an external webserver, BlueMap can be configured to be always available."_ but I couldn't find anything in config.

**Comment by oddlama** [comment]
For that you will have to configure BlueMap differently, that's not related to this projects. Have a look at https://bluemap.bluecolored.de/wiki/webserver/
