### ISSUE TITLE
Proxy + Server not starting

### ISSUE THREAD

**Issue by axldroid** [oddlama/minecraft-server#5]
What I ran:
systemctl enable --now minecraft-server minecraft-proxy

Error:
Failed to start minecraft-server.service: Unit minecraft-server.service is not loaded properly: Exec format error.
See system logs and 'systemctl status minecraft-server.service' for details.
Failed to start minecraft-proxy.service: Unit minecraft-proxy.service is not loaded properly: Exec format error.
See system logs and 'systemctl status minecraft-proxy.service' for details.

**Comment by oddlama** [comment]
This looks like you are trying to run some executable on an unsupported architecture. My best guess is that you have a wrong version of java installed, but this most likely isn't a problem with this project so I'm not sure if I can be of much help here

**Comment by axldroid** [comment]
Here's a more specific error:
 /lib/systemd/system/minecraft-proxy.service:12: Executable path is not absolute: tmux -S /run/minecraft-proxy/tmux set -g default-shell /bin/bash ";" new-session -d "/var/lib/minecraft/deploy/contrib/server_loop.py ./start.sh"

**Comment by axldroid** [comment]
I tried doing that, now I am getting a new error when trying to launch the proxy & server

```
Nov 14 18:32:42 mastersmp systemd[1]: minecraft-server.service: Control process exited, code=killed status=31
Nov 14 18:32:42 mastersmp systemd[1]: minecraft-server.service: Failed with result 'signal'.
Nov 14 18:32:42 mastersmp systemd[1]: Failed to start Minecraft server.
```

**Comment by oddlama** [comment]
This looks like your distribution is enforcing some kind of MAC policy (SELinux maybe?) for which an application profile might be missing. But I'm really grasping at straws here, you need to be familiar with your distribution to fix this. At this point I can guarantee that this isn't related to anything from this project specifically. You need to know the details about your specific system to fix this, if I had to guess I'd say you are using Fedora or a derivative where SELinux is enabled by default.

**Comment by oddlama** [comment]
They probably have some of the aforementioned restrictions in place. Glad you found a solution.
