### ISSUE TITLE
Adding GeyserMC/Bedrock Support

### ISSUE THREAD

**Issue by axldroid** [oddlama/minecraft-server#6]
Adding geyserMC might be good so that servers have bedrock support

**Comment by oddlama** [comment]
I'm open to the idea but as I don't own Bedrock myself I can't test this. If anyone else want's to implement this I'm happy to accept PRs.

**Comment by itslexwhoelse** [comment]
hey I know this issue is closed but I could take it on if it's still requested! I'll make a fork either way

**Comment by oddlama** [comment]
Of course, help is always welcome!

There actually isn't that much to be done code-wise, vane already "works" (with some issues) in geyser without modifications. The main problem right now is that we have no resource pack for bedrock players, so translations and item models don't work. Someone on the discord server (0xSoul) already got quite some stuff working in their manually created resource pack, so you might want to chat with him

**Comment by oddlama** [comment]
Sure, help is always welcome! Not sure what adding geyser support would entail exactly. Plugins like vane would probably need to be made optional in that case, since we don't have proper bedrock support in vane yet.
